---
dependencies:
  - common
  - jscover
  - role: oraclejdk

  # dependencies for edx-app jenkins worker:
  - role: edxapp_common
    when: platform_worker is defined

  # dependencies for android worker
  - role: android_sdk
    when: android_worker is defined
    # User/group to manage Android SDK
    android_user: "jenkins"
    android_group: "jenkins"
    # Tarball to download
    # old path "android-sdk_r24.4.1-linux.tgz" replaced 
    android_download: "sdk-tools-linux-4333796.zip"
    
    # Checksum of Android SDK (from: https://developer.android.com/studio/index.html#downloads)
    # Old Checksum "725bb360f0f7d04eaccff5a2d57abdd49061326d" - replaced
    android_checksum: "8c7c28554a32318461802c1291d76fccfafde054"
    
    # path to installed android sdk
    android_home: "/opt/android-sdk-linux"
    
    # The SDK version used to compile the project | 3 | Android SDK Platform 27
    android_build_targets: "\"platforms;android-27\""

    # other android dependencies that cannot be tested via the android sdk manager. instead, stat the android_test_path to test for presence of the package
# Plateform Tools | 28.0.1 | Android SDK Platform-Tools
# The BuildTools version | 27.0.3 | Android SDK Build-Tools 27.0.3
# Additional components 
# extras;google;m2repository | 58 | Google Repository
# extras;android;m2repository| 47.0.0 | Android Support Repository
    android_tools:
    - { package: "\"platform-tools\"", android_test_path: 'platform-tools' }
    - { package: "\"build-tools;27.0.3\"", android_test_path: 'build-tools/27.0.3' }
    - { package: "\"extras;google;m2repository\"", android_test_path: 'extras/google/m2repository' }
    - { package: "\"extras;android;m2repository\"", android_test_path: 'extras/android/m2repository' }


# Old implementations 
    # individual android build targets to be downloaded via the android sdk manager
    # android_build_targets:
    #     - android-23
    #     - android-21
    # # other android dependencies that cannot be tested via the android sdk manager. instead, stat the android_test_path
    # # to test for presence of the package
    # android_tools:
    #   - { package: 'platform-tools', android_test_path: 'platform-tools' }
    #   - { package: 'build-tools-23.0.3', android_test_path: 'build-tools/23.0.3' }
    #   - { package: 'extra-google-m2repository', android_test_path: 'extras/google/m2repository' }
    #   - { package: 'extra-android-m2repository', android_test_path: 'extras/android/m2repository' }
    #   - { package: 'sys-img-armeabi-v7a-android-21', android_test_path: 'system-images/android-21/default/armeabi-v7a/' }
    # #  - { package: 'sys-img-armeabi-v7a-android-23', android_test_path: 'system-images/android-23/default/armeabi-v7a/' }
    # # libraries needed for avd(android virtual device) emulation
    # android_apt_libraries:
    #   - lib32stdc++6
    #   - lib32z1

  # dependencies for loadtest driver worker
  - role: loadtest_driver
    when: loadtest_driver_worker is defined
